/**
 * Tailwind preset ported from stitch_alphatrade_ai_trading_platform/autonomous_terminal/DESIGN.md
 * and the Stitch screen mockups (executive_overview_portfolio_telemetry/code.html).
 * Keep this in sync if the Stitch design tokens change.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c0c1ff",
        "on-tertiary-fixed": "#410004",
        "on-surface": "#dfe2ed",
        "on-tertiary-container": "#5c0008",
        "primary-fixed-dim": "#c0c1ff",
        "inverse-primary": "#494bd6",
        "on-tertiary-fixed-variant": "#930013",
        background: "#0f131b",
        "surface-container-highest": "#31353d",
        "outline-variant": "#464554",
        "primary-container": "#8083ff",
        "surface-container-low": "#181c23",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#e1e0ff",
        "surface-container": "#1c2027",
        surface: "#0f131b",
        "error-container": "#93000a",
        "on-secondary": "#003824",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-primary": "#1000a9",
        error: "#ffb4ab",
        "on-primary-fixed": "#07006c",
        "on-background": "#dfe2ed",
        "on-primary-container": "#0d0096",
        "on-surface-variant": "#c7c4d7",
        "surface-container-high": "#262a32",
        "inverse-surface": "#dfe2ed",
        primary: "#c0c1ff",
        "inverse-on-surface": "#2d3038",
        "tertiary-container": "#ff5451",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-lowest": "#0a0e15",
        "secondary-container": "#00a572",
        "on-tertiary": "#68000a",
        tertiary: "#ffb3ad",
        "tertiary-fixed": "#ffdad7",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#ffdad6",
        "surface-bright": "#353941",
        "on-primary-fixed-variant": "#2f2ebe",
        outline: "#908fa0",
        "surface-variant": "#31353d",
        "surface-dim": "#0f131b",
        secondary: "#4edea3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-edge": "12px",
        "space-2xl": "32px",
        "space-xs": "4px",
        "gutter-terminal": "8px",
        "space-base": "16px",
        "space-lg": "20px",
        "space-md": "12px",
        "space-2xs": "2px",
        "space-sm": "8px",
        "space-xl": "24px",
      },
      fontFamily: {
        "label-numeric-lg": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Geist", "sans-serif"],
        "label-numeric-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "label-numeric-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "label-numeric-lg": ["18px", { lineHeight: "22px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-numeric-md": ["13px", { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["15px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-numeric-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
};
